### ISSUE TITLE
make CXX=g++ fails

### ISSUE THREAD

**Issue by tseemann** [cosmo-team/cosmo#3]
I assume it's still a bit clang++ specific.

```
% make CXX=g++

g++ -m64 -std=c++0x -pedantic-errors -W -Wall -Wextra -Wshadow -Wpointer-arith -Wcast-qual -Wunused -Wstrict-prototypes -Wmissing-prototypes -Wwrite-strings -Wbool-conversions -Wshift-overflow -Wliteral-conversion -Werror -DVERSION=\"0.5.1\" -O3 -mmmx -msse -msse2 -msse3 -msse4 -msse4.2 -march=native -DNDEBUG -DADD_REVCOMPS -DALL_DUMMIES -c io.cpp
g++: error: unrecognized command line option '-Wbool-conversions'
g++: error: unrecognized command line option '-Wshift-overflow'
g++: error: unrecognized command line option '-Wliteral-conversion'
Makefile:60: recipe for target 'io.o' failed

% g++ -v
Reading specs from /bio/linuxbrew/Cellar/gcc/5.2.0/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/specs
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/bio/linuxbrew/Cellar/gcc/5.2.0/libexec/gcc/x86_64-unknown-linux-gnu/5.2.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure --prefix=/bio/linuxbrew/Cellar/gcc/5.2.0  --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/bio/linuxbrew/opt/gmp --with-mpfr=/bio/linuxbrew/opt/mpfr --with-mpc=/bio/linuxbrew/opt/libmpc --with-isl=/bio/linuxbrew/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 5.2.0' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --disable-multilib
Thread model: posix
gcc version 5.2.0 (Homebrew gcc 5.2.0)

```

**Comment by tseemann** [comment]
And some more warnings which get treated as errors due to pedantic mode:

```
g++ -m64 -std=c++0x -pedantic-errors -W -Wall -Wextra -Wshadow -Wpointer-arith -Wcast-qual -Wunused -Wstrict-prototypes -Wmissing-prototypes -Wwrite-strings -Werror -DVERSION=\"0.5.1\" -O3 -mmmx -msse -msse2 -msse3 -msse4 -msse4.2 -march=native -DNDEBUG -DADD_REVCOMPS -DALL_DUMMIES -c io.cpp
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
cc1plus: warning: command line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
In file included from dummies.hpp:13:0,
                 from io.hpp:13,
                 from io.cpp:1:
kmer.hpp: In function 'uint8_t get_nt(const uint128_t&, uint8_t)':
kmer.hpp:40:42: error: cast from type 'const uint128_t*' to type 'uint64_t* {aka long unsigned int*}' casts away qualifiers [-Werror=cast-qual]
   uint64_t block_64 = ((uint64_t*)(&block))[block_idx];
                                          ^
In file included from io.hpp:13:0,
                 from io.cpp:1:
dummies.hpp: At global scope:
dummies.hpp:98:6: error: extra ';' [-Wpedantic]
     };
      ^
cc1plus: all warnings being treated as errors
Makefile:59: recipe for target 'io.o' failed
make: *** [io.o] Error 1
```

**Comment by winni2k** [comment]
Hmm, I just successfully compiled using gcc 7.2.0 (On the VARI branch)

**Comment by tseemann** [comment]
Not many people are able to build with gcc 7.2.0
Brew uses 4.8 (with C++11)
Conda uses 4.7 still.

**Comment by winni2k** [comment]
I agree.  I have tried and failed to get this compiled on CentOS :/

**Comment by tseemann** [comment]
@wkretzsch ok thank you for trying. i might give it another go when i have time.
